export { default as Home } from './Home'
export { default as About } from './About'
export { default as Resume } from './Resume'
export { default as Sample } from './Sample'
export { default as Comments } from './Comments'
